### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Dmole**
suspend support

### CODE REVIEW

**Comment by gaul** [comment]
I don't understand why this is necessary?  I see your comment in #148 but doesn't it seem like mbpfan can work around this in code instead of via systemd?

**Comment by Dmole** [comment]
Maybe there is a better solution, but this works.

**Comment by gaul** [comment]
The issue with solving this via systemd is that only a few users will configure it this way.  Unfortunately I cannot reproduce this on my hardware.  If you can reproduce the symptoms, please see if adding clock skew detection to the main mbpfan loop and resetting there addresses the problem.

**Comment by Dmole** [comment]
Want to put that on a branch for me?

**Comment by gaul** [comment]
You can try this:

https://github.com/dgraziotin/mbpfan/tree/recalibrate

Note that I will need more logging validation before this can merge.

**Comment by Dmole** [comment]
Restarting mbpfan is also required on that branch to quite the fans down.
The oscillation is gone (maybe due to 1s vs 7s polling).
"Clock skew" appears to happen when the suspend command is issued and again on wake.
The "Fan Speed"s act like they are cached.

```
Sleeping for 2 seconds to get first temp delta
Old Temp 38: New Temp: 39, Fan Speed: 1150
Old Temp 38: New Temp: 39, Fan Speed: 1100
Old Temp 38: New Temp: 39, Fan Speed: 940
Sleeping for 1 seconds
Old Temp 39: New Temp: 35, Fan Speed: 1150
Old Temp 39: New Temp: 35, Fan Speed: 1100
Old Temp 39: New Temp: 35, Fan Speed: 940
Sleeping for 1 seconds
...
Sleeping for 1 seconds
Old Temp 36: New Temp: 39, Fan Speed: 1150
Old Temp 36: New Temp: 39, Fan Speed: 1100
Old Temp 36: New Temp: 39, Fan Speed: 940
Sleeping for 1 seconds
Old Temp 39: New Temp: 40, Fan Speed: 1150
Old Temp 39: New Temp: 40, Fan Speed: 1100
Old Temp 39: New Temp: 40, Fan Speed: 940
Sleeping for 1 seconds
Clock skew detected - slept for 125 seconds but expected 1
Sleeping for 2 seconds to get first temp delta
Old Temp 40: New Temp: 39, Fan Speed: 1150
Old Temp 40: New Temp: 39, Fan Speed: 1100
Old Temp 40: New Temp: 39, Fan Speed: 940
Sleeping for 1 seconds
Old Temp 39: New Temp: 39, Fan Speed: 1150
Old Temp 39: New Temp: 39, Fan Speed: 1100
Old Temp 39: New Temp: 39, Fan Speed: 940
Sleeping for 1 seconds
Old Temp 39: New Temp: 39, Fan Speed: 1150
Old Temp 39: New Temp: 39, Fan Speed: 1100
Old Temp 39: New Temp: 39, Fan Speed: 940
Sleeping for 1 seconds
Old Temp 39: New Temp: 41, Fan Speed: 1150
Old Temp 39: New Temp: 41, Fan Speed: 1100
Old Temp 39: New Temp: 41, Fan Speed: 940
Sleeping for 1 seconds
Old Temp 41: New Temp: 39, Fan Speed: 1150
Old Temp 41: New Temp: 39, Fan Speed: 1100
Old Temp 41: New Temp: 39, Fan Speed: 940
Sleeping for 1 seconds
Clock skew detected - slept for 3 seconds but expected 1
Sleeping for 2 seconds to get first temp delta
Old Temp 39: New Temp: 37, Fan Speed: 1150
Old Temp 39: New Temp: 37, Fan Speed: 1100
Old Temp 39: New Temp: 37, Fan Speed: 940
...
```

**Comment by gaul** [comment]
`mbpfan` does cache the previous fan speed.  Please check out the latest recalibrate branch which may address this behavior.

**Comment by Dmole** [comment]
That did not work.

2 dead white spaces BTW;
Screenshot from 2019-10-04 01-13-27

**Comment by Dmole** [comment]
A cleaner fix was found:
https://github.com/linux-on-mac/mbpfan/issues/148#issuecomment-546133052

**Pull request closed without merging**
