### PR TITLE
Official Fedora Package #181

### PR DESCRIPTION
**Pull request by LyesSaadi**
mbpfan is _finally_ on official Fedora repository :tada:!

### CODE REVIEW

**Comment by gaul** [comment]
Thank you for your hard work!  I noticed two things when installing on my MacBook:

* mbpfan did not start automatically after `dnf install mbpfan`.  Does this start automatically on reboot?  Can it start automatically after install?
* I noticed it runs as `/usr/sbin/mbpfan -f`.  Is this the convention for systemd instead of daemonizing?

**Comment by LyesSaadi** [comment]
> Thank you for your hard work!

You're welcome :)!

> mbpfan did not start automatically after `dnf install mbpfan`.  Does this start automatically on reboot?

No, I would have to go through a special request for that according [to policy](https://docs.fedoraproject.org/en-US/packaging-guidelines/DefaultServices/#_how_to_enable_a_service_by_default). But, does mbpfan _« alter other services »_ by taking over the fans? If not, would you want me to go through the process?

> Can it start automatically after install?

No, for reasons explained [here](https://docs.fedoraproject.org/en-US/packaging-guidelines/Systemd/#_why_dont_we)

> I noticed it runs as `/usr/sbin/mbpfan -f`.  Is this the convention for systemd instead of daemonizing?

Yep, for logs when doing `systemctl status mbpfan`. And, well, I'm using the provided systemd service.

Also, thank you for being patient and allowing me to be your Fedora maintainer for mbpfan :).

**Comment by gaul** [comment]
> No, I would have to go through a special request for that according [to policy](https://docs.fedoraproject.org/en-US/packaging-guidelines/DefaultServices/#_how_to_enable_a_service_by_default). But, does mbpfan _« alter other services »_ by taking over the fans? If not, would you want me to go through the process?

This sounds reasonable.  Should the README or the post-install script suggest how to start mbpfan automatically?

> Also, thank you for being patient and allowing me to be your Fedora maintainer for mbpfan :).

Thank you for bringing mbpfan to a wider audience!

**Comment by LyesSaadi** [comment]
> This sounds reasonable.

So, do you want me to go through the process? I'm confused :/. What does sound reasonable, Fedora policy or going through the process :P. Please also bear in mind that only some services are enabled by default and none of them are hardware-dependent.

> Should the README or the post-install script suggest how to start mbpfan automatically?

The README, as post-install scripts do not display any message with DNF. And there's already [a section for that](https://github.com/linux-on-mac/mbpfan#run-instructions) :)!

**Comment by gaul** [comment]
Let's not do anything special for Fedora.  However I would like the instructions to be straightforward for beginning users who may not understand systemd.  Looking at the README, it seems like the instructions may be stale for a few distributions.  At least the Fedora section should suggest the systemd instructions?

**Pull request merged**
